controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Lower body controller - legs and waist for coordinated locomotion
    lower_body_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Separate left and right arm controllers for independent control
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Separate left and right wrist controllers for independent control
    left_wrist_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_wrist_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Separate left and right simple hand controllers for independent control
    left_simple_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_simple_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Lower body controller - coordinated locomotion
lower_body_controller:
  ros__parameters:
    joints:
      - left_hip_pitch_joint
      - left_hip_roll_joint
      - left_hip_yaw_joint
      - left_knee_joint
      - left_ankle_pitch_joint
      - left_ankle_roll_joint
      - right_hip_pitch_joint
      - right_hip_roll_joint
      - right_hip_yaw_joint
      - right_knee_joint
      - right_ankle_pitch_joint
      - right_ankle_roll_joint
      - waist_yaw_joint
      - waist_roll_joint
      - waist_pitch_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true

# Left arm controller - independent control
left_arm_controller:
  ros__parameters:
    joints:
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true

# Right arm controller - independent control
right_arm_controller:
  ros__parameters:
    joints:
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true

# Left wrist controller - independent control
left_wrist_controller:
  ros__parameters:
    joints:
      - left_wrist_roll_joint
      - left_wrist_pitch_joint
      - left_wrist_yaw_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true

# Right wrist controller - independent control
right_wrist_controller:
  ros__parameters:
    joints:
      - right_wrist_roll_joint
      - right_wrist_pitch_joint
      - right_wrist_yaw_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true

# Left simple hand controller - independent control (thumb, index, middle)
left_simple_hand_controller:
  ros__parameters:
    joints:
      - left_hand_thumb_0_joint
      - left_hand_thumb_1_joint
      - left_hand_thumb_2_joint
      - left_hand_index_0_joint
      - left_hand_index_1_joint
      - left_hand_middle_0_joint
      - left_hand_middle_1_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true

# Right simple hand controller - independent control (thumb, index, middle)
right_simple_hand_controller:
  ros__parameters:
    joints:
      - right_hand_thumb_0_joint
      - right_hand_thumb_1_joint
      - right_hand_thumb_2_joint
      - right_hand_index_0_joint
      - right_hand_index_1_joint
      - right_hand_middle_0_joint
      - right_hand_middle_1_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true 