controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    effort_controller:
      type: effort_controllers/JointGroupEffortController


joint_trajectory_controller:
  ros__parameters:  
    joints:
    - left_shoulder_roll_joint
    - left_shoulder_pitch_joint
    - left_shoulder_yaw_joint
    - right_shoulder_roll_joint
    - right_shoulder_pitch_joint
    - right_shoulder_yaw_joint
    - right_knee_joint
    - left_knee_joint

    interface_name: position
    command_interfaces:
      - position
      # - effort

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: true
    open_loop_control: true
    constraints:
      # stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      left_shoulder_pitch_joint:
        trajectory: 0.05
        goal: 0.03
      right_shoulder_pitch_joint:
        trajectory: 0.05
        goal: 0.03
      left_shoulder_roll_joint:
        trajectory: 0.05
        goal: 0.03
      right_shoulder_roll_joint:
        trajectory: 0.05
        goal: 0.03
      left_shoulder_yaw_joint:
        trajectory: 0.05
        goal: 0.03
      right_shoulder_yaw_joint:
        trajectory: 0.05
        goal: 0.03
      right_knee_joint:
        trajectory: 0.05
        goal: 0.03
      left_knee_joint:
        trajectory: 0.05
        goal: 0.03


effort_controller:
  ros__parameters:
    joints:
    - left_shoulder_roll_joint
    - left_shoulder_pitch_joint
    - left_shoulder_yaw_joint
    - right_shoulder_roll_joint
    - right_shoulder_pitch_joint
    - right_shoulder_yaw_joint
    - right_knee_joint
    - left_knee_joint

    interface_name: effort
    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      # stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      left_shoulder_pitch_joint:
        trajectory: 0.05
        goal: 0.03
      right_shoulder_pitch_joint:
        trajectory: 0.05
        goal: 0.03
      left_shoulder_roll_joint:
        trajectory: 0.05
        goal: 0.03
      right_shoulder_roll_joint:
        trajectory: 0.05
        goal: 0.03
      left_shoulder_yaw_joint:
        trajectory: 0.05
        goal: 0.03
      right_shoulder_yaw_joint:
        trajectory: 0.05
        goal: 0.03
      right_knee_joint:
        trajectory: 0.05
        goal: 0.03
      left_knee_joint:
        trajectory: 0.05
        goal: 0.03


# unitree_a1_control:
#     ros__parameters:
#         joint_state_broadcaster:
#             type: joint_state_broadcaster/JointStateBroadcaster
#             publish_rate: 1000
        
#         FL_hip_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: FL_hip_joint
#             pid:
#                 p: 100.0
#                 i: 0.0
#                 d: 5.0
    
#         FL_thigh_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: FL_thigh_joint
#             pid:
#                 p: 300.0
#                 i: 0.0
#                 d: 8.0
    
#         FL_calf_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: FL_calf_joint
#             pid:
#                 p: 300.0
#                 i: 0.0
#                 d: 8.0
    
#         FR_hip_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: FR_hip_joint
#             pid:
#                 p: 100.0
#                 i: 0.0
#                 d: 5.0
    
#         FR_thigh_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: FR_thigh_joint
#             pid:
#                 p: 300.0
#                 i: 0.0
#                 d: 8.0
    
#         FR_calf_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: FR_calf_joint
#             pid:
#                 p: 300.0
#                 i: 0.0
#                 d: 8.0
    
#         RL_hip_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: RL_hip_joint
#             pid:
#                 p: 100.0
#                 i: 0.0
#                 d: 5.0
    
#         RL_thigh_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: RL_thigh_joint
#             pid:
#                 p: 300.0
#                 i: 0.0
#                 d: 8.0
    
#         RL_calf_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: RL_calf_joint
#             pid:
#                 p: 300.0
#                 i: 0.0
#                 d: 8.0

#         RR_hip_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: RR_hip_joint
#             pid:
#                 p: 100.0
#                 i: 0.0
#                 d: 5.0

#             RR_thigh_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: RR_thigh_joint
#             pid:
#                 p: 300.0
#                 i: 0.0
#                 d: 8.0

#             RR_calf_controller:
#             type: unitree_legged_control/UnitreeJointController
#             joint: RR_calf_joint
#             pid:
#                 p: 300.0
#                 i: 0.0
#                 d: 8.0