controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    effort_controller:
      type: effort_controllers/JointGroupEffortController


joint_trajectory_controller:
  ros__parameters:  
    joints:
      # Leg joints (position control only)
      - left_hip_yaw_joint
      - left_hip_roll_joint
      - left_hip_pitch_joint
      - left_knee_joint
      - left_ankle_joint
      - right_hip_yaw_joint
      - right_hip_roll_joint
      - right_hip_pitch_joint
      - right_knee_joint
      - right_ankle_joint
      - torso_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    open_loop_control: true
    constraints:
      goal_time: 0.0
      # Leg constraints
      left_hip_yaw_joint: {trajectory: 0.05, goal: 0.03}
      left_hip_roll_joint: {trajectory: 0.05, goal: 0.03}
      left_hip_pitch_joint: {trajectory: 0.05, goal: 0.03}
      left_knee_joint: {trajectory: 0.05, goal: 0.03}
      left_ankle_joint: {trajectory: 0.05, goal: 0.03}
      right_hip_yaw_joint: {trajectory: 0.05, goal: 0.03}
      right_hip_roll_joint: {trajectory: 0.05, goal: 0.03}
      right_hip_pitch_joint: {trajectory: 0.05, goal: 0.03}
      right_knee_joint: {trajectory: 0.05, goal: 0.03}
      right_ankle_joint: {trajectory: 0.05, goal: 0.03}
      torso_joint: {trajectory: 0.05, goal: 0.03}

effort_controller:
  ros__parameters:
    joints:
      # Arm joints (effort control)
      - left_shoulder_roll_joint
      - left_shoulder_pitch_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
      - left_hand_joint
      - right_shoulder_roll_joint
      - right_shoulder_pitch_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint
      - right_hand_joint

    interface_name: effort
    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      goal_time: 0.0
      left_shoulder_pitch_joint: {trajectory: 0.05, goal: 0.03}
      left_shoulder_roll_joint: {trajectory: 0.05, goal: 0.03}
      left_shoulder_yaw_joint: {trajectory: 0.05, goal: 0.03}
      left_elbow_joint: {trajectory: 0.05, goal: 0.03}
      left_hand_joint: {trajectory: 0.05, goal: 0.03}
      right_shoulder_pitch_joint: {trajectory: 0.05, goal: 0.03}
      right_shoulder_roll_joint: {trajectory: 0.05, goal: 0.03}
      right_shoulder_yaw_joint: {trajectory: 0.05, goal: 0.03}
      right_elbow_joint: {trajectory: 0.05, goal: 0.03}
      right_hand_joint: {trajectory: 0.05, goal: 0.03}
